version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: litestar_intro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/litestar_intro
      DEBUG: 0

volumes:
  postgres_data:

networks:
  backend:
