[project]
name = "litestar-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "litestar-users>=1.7.0",
    "litestar[standart]>=2.15.2",
    "sqlalchemy>=2.0.40",
    "uvicorn>=0.34.0",
]
